bindkey "^[OC" forward-word
bindkey "^[OD" backward-word
bindkey "^[[0~" beginning-of-line
bindkey "^[OH" beginning-of-line
bindkey "^[[H" beginning-of-line
bindkey "[1~" beginning-of-line
bindkey "^[[4~" end-of-line
bindkey "^[[F" end-of-line
bindkey "^[OF" end-of-line
bindkey "[3~" delete-char
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "[5~" up-line-or-history
bindkey "[6~" down-line-or-history
bindkey "[2~" quote-line
bindkey "^R" history-incremental-search-backward
bindkey "^[[1;3D" backward-delete-word
bindkey "^[[1;3C" delete-word
