
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

hl.config {{ autogenerated = true }}

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "alacritty"
local fileManager = "dolphin"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
   hl.exec_cmd("dms run")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 3,
        gaps_out = 5,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "scrolling",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- DankMaterialShell-generated settings (override the look-and-feel values above)
local dmsDir = os.getenv("HOME") .. "/.config/hypr/dms/"
--dofile(dmsDir .. "binds.lua")
dofile(dmsDir .. "layout.lua")
dofile(dmsDir .. "outputs.lua")
dofile(dmsDir .. "windowrules.lua")
dofile(dmsDir .. "alttab.lua")
dofile(dmsDir .. "colors.lua")
dofile(dmsDir .. "cursor.lua")
dofile(dmsDir .. "wpblur.lua")

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
        wrap_focus   = false, -- niri does not wrap column focus/moves
        wrap_swapcol = false,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us,ru",
        kb_variant = "altgr-intl,",
        kb_model   = "",
        kb_options = "grp:caps_toggle,level3:ralt_switch",
        kb_rules   = "",
        numlock_by_default = true,

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- Binds mirror ~/.config/niri/config.kdl (niri "Mod" = Alt).
-- Column operations rely on the scrolling layout (general.layout above).
local mainMod = "ALT"
local superMod = "SUPER"

local function bind(keys, dispatcher, opts)
    hl.bind(mainMod .. " + " .. keys, dispatcher, opts)
end

-- Apps / session
bind("D",              hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
bind("F2",             hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
bind("SHIFT + RETURN", hl.dsp.exec_cmd(terminal))
bind("O",              hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))
hl.bind(superMod .. " + L",           hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind(superMod .. " + ALT + S",     hl.dsp.exec_cmd("pkill orca || exec orca"), { locked = true })
bind("CTRL + minus",   hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
-- DPMS from a bind directly is discouraged by the wiki; defer it with a timer
bind("SHIFT + P", function()
    hl.timer(function()
        hl.dispatch(hl.dsp.dpms({ action = "disable" }))
    end, { timeout = 500, type = "oneshot" })
end)

-- Close window
bind("F4",        hl.dsp.window.close())
bind("SHIFT + C", hl.dsp.window.close())

-- Focus columns / windows
bind("left",  hl.dsp.focus({ direction = "l" }))
bind("right", hl.dsp.focus({ direction = "r" }))
bind("up",    hl.dsp.focus({ direction = "u" }))
bind("down",  hl.dsp.focus({ direction = "d" }))
bind("H",     hl.dsp.focus({ direction = "l" }))
bind("L",     hl.dsp.focus({ direction = "r" }))
bind("K",     hl.dsp.focus({ direction = "u" }))
bind("J",     hl.dsp.focus({ direction = "d" }))

-- Move columns / windows
bind("SHIFT + left",  hl.dsp.layout("swapcol l"))
bind("SHIFT + right", hl.dsp.layout("swapcol r"))
bind("SHIFT + up",    hl.dsp.window.move({ direction = "u" }))
bind("SHIFT + down",  hl.dsp.window.move({ direction = "d" }))
bind("CTRL + H",      hl.dsp.layout("swapcol l"))
bind("CTRL + L",      hl.dsp.layout("swapcol r"))
bind("CTRL + K",      hl.dsp.window.move({ direction = "u" }))
bind("CTRL + J",      hl.dsp.window.move({ direction = "d" }))

-- Monitors
bind("Q",         hl.dsp.focus({ monitor = "l" }))
bind("E",         hl.dsp.focus({ monitor = "r" }))
bind("SHIFT + H", hl.dsp.focus({ monitor = "l" }))
bind("SHIFT + L", hl.dsp.focus({ monitor = "r" }))
bind("SHIFT + K", hl.dsp.focus({ monitor = "u" }))
bind("SHIFT + J", hl.dsp.focus({ monitor = "d" }))

bind("SHIFT + Q",        hl.dsp.window.move({ monitor = "l" }))
bind("SHIFT + E",        hl.dsp.window.move({ monitor = "r" }))
bind("SHIFT + CTRL + H", hl.dsp.window.move({ monitor = "l" }))
bind("SHIFT + CTRL + L", hl.dsp.window.move({ monitor = "r" }))
bind("SHIFT + CTRL + K", hl.dsp.window.move({ monitor = "u" }))
bind("SHIFT + CTRL + J", hl.dsp.window.move({ monitor = "d" }))
bind("SHIFT + CTRL + up",   hl.dsp.window.move({ monitor = "u" }))
bind("SHIFT + CTRL + down", hl.dsp.window.move({ monitor = "d" }))

bind("SHIFT + CTRL + left",  hl.dsp.workspace.move({ monitor = "l" }))
bind("SHIFT + CTRL + right", hl.dsp.workspace.move({ monitor = "r" }))

-- Workspaces up/down (per monitor, including the next empty one like niri)
bind("Page_Down",        hl.dsp.focus({ workspace = "r+1" }))
bind("Page_Up",          hl.dsp.focus({ workspace = "r-1" }))
bind("U",                hl.dsp.focus({ workspace = "r+1" }))
bind("I",                hl.dsp.focus({ workspace = "r-1" }))
bind("CTRL + Page_Down", hl.dsp.window.move({ workspace = "r+1" }))
bind("CTRL + Page_Up",   hl.dsp.window.move({ workspace = "r-1" }))
bind("SHIFT + U",        hl.dsp.window.move({ workspace = "r+1" }))
bind("SHIFT + I",        hl.dsp.window.move({ workspace = "r-1" }))

bind("mouse_down",              hl.dsp.focus({ workspace = "r+1" }))
bind("mouse_up",                hl.dsp.focus({ workspace = "r-1" }))
bind("CTRL + mouse_down",       hl.dsp.window.move({ workspace = "r+1" }))
bind("CTRL + mouse_up",         hl.dsp.window.move({ workspace = "r-1" }))
bind("SHIFT + mouse_down",      hl.dsp.focus({ direction = "r" }))
bind("SHIFT + mouse_up",        hl.dsp.focus({ direction = "l" }))
bind("CTRL + SHIFT + mouse_down", hl.dsp.layout("swapcol r"))
bind("CTRL + SHIFT + mouse_up",   hl.dsp.layout("swapcol l"))

-- Mod+[1-9] focuses a workspace, Mod+Ctrl+[1-9] moves the window there
for i = 1, 9 do
    bind(tostring(i),          hl.dsp.focus({ workspace = i }))
    bind("CTRL + " .. i,       hl.dsp.window.move({ workspace = i }))
end

-- Column composition
bind("bracketleft",  hl.dsp.layout("consume_or_expel prev"))
bind("bracketright", hl.dsp.layout("consume_or_expel next"))
bind("comma",        hl.dsp.layout("consume"))
bind("period",       hl.dsp.layout("expel"))

-- Sizing
bind("R",             hl.dsp.layout("colresize +conf"))
bind("SHIFT + R",     hl.dsp.layout("colresize -conf"))
bind("A",             hl.dsp.layout("colresize 1.0"))
bind("CTRL + F",      hl.dsp.layout("fit expand"))
bind("C",             hl.dsp.layout("fit_into_view"))
bind("CTRL + C",      hl.dsp.layout("fit visible"))
bind("minus",         hl.dsp.layout("colresize -0.1"))
bind("equal",         hl.dsp.layout("colresize +0.1"))
bind("SHIFT + minus", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))
bind("SHIFT + equal", hl.dsp.window.resize({ x = 0, y = 100, relative = true }))
bind("SHIFT + F",     hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
bind("M",             hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))

-- Floating / tabs
bind("V", hl.dsp.window.float({ action = "toggle" }))
bind("SHIFT + V", function()
    local w = hl.get_active_window()
    if w and w.floating then
        hl.dispatch(hl.dsp.window.cycle_next({ tiled = true }))
    else
        hl.dispatch(hl.dsp.window.cycle_next({ floating = true }))
    end
end)
bind("W", hl.dsp.group.toggle())

-- Screenshots
hl.bind("Print",              hl.dsp.exec_cmd("dms screenshot region"))
hl.bind("CTRL + Print",       hl.dsp.exec_cmd("dms screenshot full"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("dms screenshot window"))

-- Move/resize windows with mainMod + LMB/RMB and dragging
bind("mouse:272", hl.dsp.window.drag(),   { mouse = true })
bind("mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Media keys (allowed while locked, as in niri)
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+ -l 1.0"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-"),        { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),        { locked = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),      { locked = true })
hl.bind("XF86AudioPlay",         hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioStop",         hl.dsp.exec_cmd("playerctl stop"),       { locked = true })
hl.bind("XF86AudioPrev",         hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
hl.bind("XF86AudioNext",         hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl --class=backlight set +10%"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl --class=backlight set 10%-"), { locked = true, repeating = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})


---------------------------------
---- NAMED WORKSPACES (niri) ----
---------------------------------

-- Mirrors the named workspaces / open-on-workspace rules in ~/.config/niri/config.kdl
-- Workspaces with an id are regular numbered workspaces (so r+1/r-1 and Mod+N reach them)
-- labelled with default_name; the rest are pure named workspaces.
local namedWorkspaces = {
    { name = "web",   monitor = "HDMI-A-1", id = 1 },
    { name = "code",  monitor = "HDMI-A-1", id = 2 },
    { name = "docs",  monitor = "HDMI-A-1", id = 3 },
    { name = "chats", monitor = "eDP-1", id = 8 },
    { name = "media", monitor = "eDP-1", id = 9 },
}

local workspaceSelector = {}
for _, ws in ipairs(namedWorkspaces) do
    local selector = ws.id and tostring(ws.id) or ("name:" .. ws.name)
    workspaceSelector[ws.name] = selector
    hl.workspace_rule({
        workspace    = selector,
        default_name = ws.id and ws.name or nil,
        monitor      = ws.monitor,
        persistent   = true,
    })
end

local workspaceApps = {
    web = {
        "^chromium-browser-beta$",
        "^firefox$",
        "^librewolf$",
    },
    chats = {
        "^org\\.telegram\\.desktop$",
        "^com\\.slack\\.Slack$",
        "^org\\.kde\\.kmail2$",
        "^thunderbird$",
        "^max$",
        "^org\\.squidowl\\.halloy$",
        "^discord$",
        "^org\\.kde\\.kontact$",
        "com.rtosta.zapzap",
    },
    media = {
        "^org\\.kde\\.kasts$",
        "^vlc$",
        "^org\\.kde\\.ktorrent$",
        "org.kde.elisa",
    },
    code = {
        "^com.anthropic.Claude$",
        "^chatgpt$",
        "^dev.zed.Zed$",
    },
    docs = {
        "^obsidian$",
        "^md.Obsidian$",
        "md.obsidian.Obsidian",
    },
}

for ws, classes in pairs(workspaceApps) do
    for _, class in ipairs(classes) do
        hl.window_rule({
            name      = "workspace-" .. ws .. "-" .. class,
            match     = { class = class },
            workspace = workspaceSelector[ws],
        })
    end
end

-- Floating / fullscreen rules
hl.window_rule({
    name  = "float-telegram-dialogs",
    match = {
        class = "^org\\.telegram\\.desktop$",
        title = "^(Media viewer|Media View|Choose Files|Open File|Save File)$",
    },
    float = true,
})

for _, class in ipairs({ "^winecfg\\.exe$", "^game\\.exe$", "^syncthingtray$" }) do
    hl.window_rule({
        name  = "float-" .. class,
        match = { class = class },
        float = true,
    })
end

hl.window_rule({
    name  = "float-firefox-pip",
    match = { class = "firefox$", title = "^Picture-in-Picture$" },
    float = true,
})

hl.window_rule({
    name       = "fullscreen-vlc",
    match      = { class = "^vlc$" },
    fullscreen = true,
})
